In [11]:
import numpy as np

arr = np.random.randint(100, size=(10, 3))
print(arr)


[[83 36 61]
 [48 29 78]
 [19  9 82]
 [88 69 71]
 [64 69 66]
 [59 16 65]
 [93 23 68]
 [78 38 16]
 [93 79 99]
 [16 87 66]]
